In [ ]:
from hallmark.eht_repo_builder import build_repo

L1_datasets = {
    "EHTC_2017L1_May2022": [
        {"fmt": "{project_code}/group.uid{guid}.{author}.{kind}.{format}",
         "db": "description.tsv"},
        {"fmt": 
         "{eht_project_code}/group.uid{guid}.{author}.{scope}-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".{prefix}track{track}-{date}.app_deliverables.{format}",
         "db": "deliverables.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.{track}-{alma_band}-"
        "{eht_band}-{source}-{scan_code}-{sequence}-{kind}.{format}",
         "db": "data.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.metadata-"
         "{eht_product_code}.{format}",
         "db": "meta.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".EHTmetadata_{meta_id}.{format}",
         "db": "meta.tsv"},
        {"name": "checksum",
         "fmt": "{eht_project_code}.{algorithm}sums",
         "db": "checksums.tsv"}],
    "EHTC_2018L1_Dec2024": [
        {"fmt": 
         "{project_date}/{project_code}/group.uid{guid}.{author}.description.{format}",
         "db": "description.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.{track}"
         "-{obs_num}-{band}-{pointing}-{source}-{kind}.{format}",
         "db": "data.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.{scope}"
         "-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".{prefix}track{track}-{date}.app_deliverables.{format}",
         "db": "deliverables.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.metadata-"
         "{meta_id}.{format}",
         "db": "meta.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".EHTmetadata_{meta_id}.{format}",
         "db": "meta.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/{source}-v{version}-{kind}.{format}",
         "db": "Oct2018.tsv"},
        {"fmt": 
         "{project_date}/{eht_project_code}/group.uid{guid}.{author}.md5sum.{format}",
         "db": "checksums.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".readme-metadata-update-v{old_version}-to-v{new_version}.{format}",
         "db": "readme_updates.tsv"}],
    "EHTC_2021L1_Dec2025": [
        {"fmt": "{project_code}/group.uid{guid}.{author}.description.{format}",
         "db": "description.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.{track}-{obs_num}-{band}"
         "-{pointing}-{source}-{kind}.{format}",
         "db": "data.tsv"},
        {"fmt": 
         "{eht_project_code}/group.uid{guid}.{author}.{scope}-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt": 
         "{eht_project_code}/group.uid{guid}.{author}.metadata-{meta_id}.{meta_ext}",
         "db": "meta.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.md5sum.{format}",
         "db": "checksums.tsv"},]
}
dataset_names = list(L1_datasets.keys())
L1_idx = 0
dataset_name = dataset_names[L1_idx]

repo = build_repo(
    repo_path=f"/home/samj98/hallmark_outputs/{dataset_name}.hm",
    dataset_name=dataset_name,
    fmt_entries=L1_datasets[dataset_name],
    remotes=[{"name": "origin"}])

In [ ]:
import pandas as pd
from IPython.display import display

print("=== config.yml ===")
print((repo.dothm.path / "config.yml").read_text())

for tsv_path in sorted(repo.dothm.path.glob("*.tsv")):
    print(f"=== {tsv_path.name} ===")
    df = pd.read_csv(tsv_path, sep="\t")
    display(df)

In [14]:
from hallmark.eht_repo_builder import build_repo

L2_dataset_names = ["EHTC_CenA2017_Jul2021", "EHTC_First3C279Results_May2020",
                    "EHTC_FirstM87Results_Apr2019", "EHTC_FirstSgrAPol_Mar2024",
                    "EHTC_FirstSgrAResults_May2022", "EHTC_M87-2018_Mar2024",
                    "EHTC_M87mwl2017_Apr2021", "EHTC_M87mwl2018_Dec2024",
                    "EHTC_M87pol2017_Nov2023", "EHTC_metadata2018_Dec2023",
                    "EHTC_MonitoringM87_Sep2020", "EHTC_SgrAmwl2017_May2022"]
L2_idx = 4
L2_dataset_name = L2_dataset_names[L2_idx]

repo_no_fmts = build_repo(
    repo_path=f"/home/samj98/hallmark_outputs/{L2_dataset_name}.hm",
    dataset_name=L2_dataset_name,
    fmt_entries=None,
    remotes=[{"name": "origin"}])

In [15]:
import pandas as pd
from IPython.display import display

print("=== config.yml ===")
print((repo_no_fmts.dothm.path / "config.yml").read_text())

for tsv_path in sorted(repo_no_fmts.dothm.path.glob("*.tsv")):
    print(f"=== {tsv_path.name} ===")
    df = pd.read_csv(tsv_path, sep="\t")
    display(df)

=== config.yml ===
data:
- file: EHTC_FirstSgrAResults_May2022_csv.tgz
  md5: 5085db038653a84dc59834ecabd35e21
- file: EHTC_FirstSgrAResults_May2022_txt.tgz
  md5: 594d99f8e9b6b4afdcd462fd592db7e5
- file: EHTC_FirstSgrAResults_May2022_uvfits.tgz
  md5: a95c5f37d26e2f2eb8a8520252e77b64
- name: inventory
  file: INVENTORY.txt
  md5: 17985c2cb2599c705a4c75834dca2bd9
- name: license
  file: LICENSE.txt
  md5: 7177765c4d9d3ba7d74281362186c926
- name: readme
  file: README.md
  md5: 9a56886c1e9581298ead967c72ede14e
- file: csv/ER6_SGRA_2017_096_hi_casa_netcal-LMTcal_StokesI.csv
  md5: bd4a5a47ab2c001d07d55482349ac6e6
- file: csv/ER6_SGRA_2017_096_hi_hops_netcal-LMTcal_StokesI.csv
  md5: aaf73f5028d00888d21500f170e472d8
- file: csv/ER6_SGRA_2017_096_lo_casa_netcal-LMTcal_StokesI.csv
  md5: 03003c9011e945a5913dae531039f075
- file: csv/ER6_SGRA_2017_096_lo_hops_netcal-LMTcal_StokesI.csv
  md5: 267217931ff91eaeb9adff569b4121b2
- file: csv/ER6_SGRA_2017_097_hi_casa_netcal-LMTcal_StokesI.csv
  md5: f1b43a4dcf88419a367849347679a6fe
- file: csv/ER6_SGRA_2017_097_hi_hops_netcal-LMTcal_StokesI.csv
  md5: df9a14dba16c3b6908db3f1805cf72b2
- file: csv/ER6_SGRA_2017_097_lo_casa_netcal-LMTcal_StokesI.csv
  md5: 51df39219c3ac2896cd8a6e21e3af513
- file: csv/ER6_SGRA_2017_097_lo_hops_netcal-LMTcal_StokesI.csv
  md5: 6c38463cc5afc8984316e15470e0f0ee
- file: csv/dump_csv.py
  md5: bfe6f6a0457cc88e4ce877a4714e740d
- file: csv_besttime/dump_csv.py
  md5: bfe6f6a0457cc88e4ce877a4714e740d
- file: csv_norm/dump_csv.py
  md5: bfe6f6a0457cc88e4ce877a4714e740d
- name: run
  file: run.sh
  md5: b8d8469f32187bc232616d3013bb250e
- file: txt/ER6_SGRA_2017_096_hi_casa_netcal-LMTcal_StokesI.txt
  md5: 26f29375d19e8f9441d2e6d3a89169cb
- file: txt/ER6_SGRA_2017_096_hi_hops_netcal-LMTcal_StokesI.txt
  md5: d1e5edf0c253cffea6ef143ba0a899c5
- file: txt/ER6_SGRA_2017_096_lo_casa_netcal-LMTcal_StokesI.txt
  md5: 5f705fae24f96f57639ce2df2dcdbf08
- file: txt/ER6_SGRA_2017_096_lo_hops_netcal-LMTcal_StokesI.txt
  md5: 20df1793ab8e9b5bed2cb9cf4b58fbb3
- file: txt/ER6_SGRA_2017_097_hi_casa_netcal-LMTcal_StokesI.txt
  md5: 07455decfec756450ae1e27a2ef629c9
- file: txt/ER6_SGRA_2017_097_hi_hops_netcal-LMTcal_StokesI.txt
  md5: b98288ade44a52e74645ff4541651f3d
- file: txt/ER6_SGRA_2017_097_lo_casa_netcal-LMTcal_StokesI.txt
  md5: d4587f280cb947008ceb59b0307ff308
- file: txt/ER6_SGRA_2017_097_lo_hops_netcal-LMTcal_StokesI.txt
  md5: 2dfb657f1873e1424a8a95ad9a8c0ef5
- file: txt/dump_txt.py
  md5: 5e1e322fcb331ec3dac97fd5f6f7db0a
- file: txt_besttime/dump_txt.py
  md5: 5e1e322fcb331ec3dac97fd5f6f7db0a
- file: txt_norm/dump_txt.py
  md5: 5e1e322fcb331ec3dac97fd5f6f7db0a
- file: uvfits/ER6_SGRA_2017_096_hi_casa_netcal-LMTcal_StokesI.uvfits
  md5: 6cd95ae7a710f827f58297441b4d1e2b
- file: uvfits/ER6_SGRA_2017_096_hi_hops_netcal-LMTcal_StokesI.uvfits
  md5: eac2c34445b338a5ea03a709008781f3
- file: uvfits/ER6_SGRA_2017_096_lo_casa_netcal-LMTcal_StokesI.uvfits
  md5: 95b52409d68cca660c954e1341384c5d
- file: uvfits/ER6_SGRA_2017_096_lo_hops_netcal-LMTcal_StokesI.uvfits
  md5: e7958dfb964889590d70c66e50bf56c2
- file: uvfits/ER6_SGRA_2017_097_hi_casa_netcal-LMTcal_StokesI.uvfits
  md5: d61879a0703d9e071c7b1f7189d4f1e5
- file: uvfits/ER6_SGRA_2017_097_hi_hops_netcal-LMTcal_StokesI.uvfits
  md5: 5b3bc75754faa7a489c9acc59f56378d
- file: uvfits/ER6_SGRA_2017_097_lo_casa_netcal-LMTcal_StokesI.uvfits
  md5: 79d849b1d65325c7a04f80992aa9db9a
- file: uvfits/ER6_SGRA_2017_097_lo_hops_netcal-LMTcal_StokesI.uvfits
  md5: bd79a1022f56beb0b881d2f29d0fb0a0
- file: uvfits/convert_stokesI.py
  md5: ef3978fcf5937ae386ee3c2658c10b8c
- file: uvfits_besttime/convert_stokesI.py
  md5: 08f395cf0a85fab656ded4cc4d006bcf
- file: uvfits_norm/convert_stokesI.py
  md5: 44347ed4a03fd479c0bb54c35bc8ff46
- fmt: '{p0}/ER6_SGRA_2017_{scan}_{band}_{pipeline}_netcal_StokesI.{p4}'
  db: data.tsv
- fmt: '{p0}_{method}/ER6_SGRA_2017_{scan}_{band}_{pipeline}_netcal-LMTcal-{p5}_StokesI.{p6}'
  db: fmt_2.tsv
remote:
- name: origin
  url: https://data.cyverse.org/dav-anon/iplant/commons/cyverse_curated/EHTC_FirstSgrAResults_May2022/

=== data.tsv ===

,path,checksum_algorithm,checksum,p0,scan,band,pipeline,p4
0,csv/ER6_SGRA_2017_096_hi_casa_netcal_StokesI.csv,NaN,NaN,csv,96,hi,casa,csv
1,csv/ER6_SGRA_2017_096_hi_hops_netcal_StokesI.csv,NaN,NaN,csv,96,hi,hops,csv
2,csv/ER6_SGRA_2017_096_lo_casa_netcal_StokesI.csv,NaN,NaN,csv,96,lo,casa,csv
3,csv/ER6_SGRA_2017_096_lo_hops_netcal_StokesI.csv,NaN,NaN,csv,96,lo,hops,csv
4,csv/ER6_SGRA_2017_097_hi_casa_netcal_StokesI.csv,NaN,NaN,csv,97,hi,casa,csv
5,csv/ER6_SGRA_2017_097_hi_hops_netcal_StokesI.csv,NaN,NaN,csv,97,hi,hops,csv
6,csv/ER6_SGRA_2017_097_lo_casa_netcal_StokesI.csv,NaN,NaN,csv,97,lo,casa,csv
7,csv/ER6_SGRA_2017_097_lo_hops_netcal_StokesI.csv,NaN,NaN,csv,97,lo,hops,csv
8,txt/ER6_SGRA_2017_096_hi_casa_netcal_StokesI.txt,NaN,NaN,txt,96,hi,casa,txt
9,txt/ER6_SGRA_2017_096_hi_hops_netcal_StokesI.txt,NaN,NaN,txt,96,hi,hops,txt
10,txt/ER6_SGRA_2017_096_lo_casa_netcal_StokesI.txt,NaN,NaN,txt,96,lo,casa,txt
11,txt/ER6_SGRA_2017_096_lo_hops_netcal_StokesI.txt,NaN,NaN,txt,96,lo,hops,txt
12,txt/ER6_SGRA_2017_097_hi_casa_netcal_StokesI.txt,NaN,NaN,txt,97,hi,casa,txt
13,txt/ER6_SGRA_2017_097_hi_hops_netcal_StokesI.txt,NaN,NaN,txt,97,hi,hops,txt
14,txt/ER6_SGRA_2017_097_lo_casa_netcal_StokesI.txt,NaN,NaN,txt,97,lo,casa,txt
15,txt/ER6_SGRA_2017_097_lo_hops_netcal_StokesI.txt,NaN,NaN,txt,97,lo,hops,txt
16,uvfits/ER6_SGRA_2017_096_hi_casa_netcal_Stokes...,NaN,NaN,uvfits,96,hi,casa,uvfits
17,uvfits/ER6_SGRA_2017_096_hi_hops_netcal_Stokes...,NaN,NaN,uvfits,96,hi,hops,uvfits
18,uvfits/ER6_SGRA_2017_096_lo_casa_netcal_Stokes...,NaN,NaN,uvfits,96,lo,casa,uvfits
19,uvfits/ER6_SGRA_2017_096_lo_hops_netcal_Stokes...,NaN,NaN,uvfits,96,lo,hops,uvfits
20,uvfits/ER6_SGRA_2017_097_hi_casa_netcal_Stokes...,NaN,NaN,uvfits,97,hi,casa,uvfits
21,uvfits/ER6_SGRA_2017_097_hi_hops_netcal_Stokes...,NaN,NaN,uvfits,97,hi,hops,uvfits
22,uvfits/ER6_SGRA_2017_097_lo_casa_netcal_Stokes...,NaN,NaN,uvfits,97,lo,casa,uvfits
23,uvfits/ER6_SGRA_2017_097_lo_hops_netcal_Stokes...,NaN,NaN,uvfits,97,lo,hops,uvfits

=== fmt_2.tsv ===

,path,checksum_algorithm,checksum,p0,method,scan,band,pipeline,p5,p6
0,csv_besttime/ER6_SGRA_2017_097_hi_casa_netcal-...,NaN,NaN,csv,besttime,97,hi,casa,besttime,csv
1,csv_besttime/ER6_SGRA_2017_097_hi_hops_netcal-...,NaN,NaN,csv,besttime,97,hi,hops,besttime,csv
2,csv_besttime/ER6_SGRA_2017_097_lo_casa_netcal-...,NaN,NaN,csv,besttime,97,lo,casa,besttime,csv
3,csv_besttime/ER6_SGRA_2017_097_lo_hops_netcal-...,NaN,NaN,csv,besttime,97,lo,hops,besttime,csv
4,csv_norm/ER6_SGRA_2017_096_hi_casa_netcal-LMTc...,NaN,NaN,csv,norm,96,hi,casa,norm,csv
5,csv_norm/ER6_SGRA_2017_096_hi_hops_netcal-LMTc...,NaN,NaN,csv,norm,96,hi,hops,norm,csv
6,csv_norm/ER6_SGRA_2017_096_lo_casa_netcal-LMTc...,NaN,NaN,csv,norm,96,lo,casa,norm,csv
7,csv_norm/ER6_SGRA_2017_096_lo_hops_netcal-LMTc...,NaN,NaN,csv,norm,96,lo,hops,norm,csv
8,csv_norm/ER6_SGRA_2017_097_hi_casa_netcal-LMTc...,NaN,NaN,csv,norm,97,hi,casa,norm,csv
9,csv_norm/ER6_SGRA_2017_097_hi_hops_netcal-LMTc...,NaN,NaN,csv,norm,97,hi,hops,norm,csv
10,csv_norm/ER6_SGRA_2017_097_lo_casa_netcal-LMTc...,NaN,NaN,csv,norm,97,lo,casa,norm,csv
11,csv_norm/ER6_SGRA_2017_097_lo_hops_netcal-LMTc...,NaN,NaN,csv,norm,97,lo,hops,norm,csv
12,txt_besttime/ER6_SGRA_2017_097_hi_casa_netcal-...,NaN,NaN,txt,besttime,97,hi,casa,besttime,txt
13,txt_besttime/ER6_SGRA_2017_097_hi_hops_netcal-...,NaN,NaN,txt,besttime,97,hi,hops,besttime,txt
14,txt_besttime/ER6_SGRA_2017_097_lo_casa_netcal-...,NaN,NaN,txt,besttime,97,lo,casa,besttime,txt
15,txt_besttime/ER6_SGRA_2017_097_lo_hops_netcal-...,NaN,NaN,txt,besttime,97,lo,hops,besttime,txt
16,txt_norm/ER6_SGRA_2017_096_hi_casa_netcal-LMTc...,NaN,NaN,txt,norm,96,hi,casa,norm,txt
17,txt_norm/ER6_SGRA_2017_096_hi_hops_netcal-LMTc...,NaN,NaN,txt,norm,96,hi,hops,norm,txt
18,txt_norm/ER6_SGRA_2017_096_lo_casa_netcal-LMTc...,NaN,NaN,txt,norm,96,lo,casa,norm,txt
19,txt_norm/ER6_SGRA_2017_096_lo_hops_netcal-LMTc...,NaN,NaN,txt,norm,96,lo,hops,norm,txt
20,txt_norm/ER6_SGRA_2017_097_hi_casa_netcal-LMTc...,NaN,NaN,txt,norm,97,hi,casa,norm,txt
21,txt_norm/ER6_SGRA_2017_097_hi_hops_netcal-LMTc...,NaN,NaN,txt,norm,97,hi,hops,norm,txt
22,txt_norm/ER6_SGRA_2017_097_lo_casa_netcal-LMTc...,NaN,NaN,txt,norm,97,lo,casa,norm,txt
23,txt_norm/ER6_SGRA_2017_097_lo_hops_netcal-LMTc...,NaN,NaN,txt,norm,97,lo,hops,norm,txt
24,uvfits_besttime/ER6_SGRA_2017_097_hi_casa_netc...,NaN,NaN,uvfits,besttime,97,hi,casa,besttime,uvfits
25,uvfits_besttime/ER6_SGRA_2017_097_hi_hops_netc...,NaN,NaN,uvfits,besttime,97,hi,hops,besttime,uvfits
26,uvfits_besttime/ER6_SGRA_2017_097_lo_casa_netc...,NaN,NaN,uvfits,besttime,97,lo,casa,besttime,uvfits
27,uvfits_besttime/ER6_SGRA_2017_097_lo_hops_netc...,NaN,NaN,uvfits,besttime,97,lo,hops,besttime,uvfits
28,uvfits_norm/ER6_SGRA_2017_096_hi_casa_netcal-L...,NaN,NaN,uvfits,norm,96,hi,casa,norm,uvfits
29,uvfits_norm/ER6_SGRA_2017_096_hi_hops_netcal-L...,NaN,NaN,uvfits,norm,96,hi,hops,norm,uvfits
30,uvfits_norm/ER6_SGRA_2017_096_lo_casa_netcal-L...,NaN,NaN,uvfits,norm,96,lo,casa,norm,uvfits
31,uvfits_norm/ER6_SGRA_2017_096_lo_hops_netcal-L...,NaN,NaN,uvfits,norm,96,lo,hops,norm,uvfits
32,uvfits_norm/ER6_SGRA_2017_097_hi_casa_netcal-L...,NaN,NaN,uvfits,norm,97,hi,casa,norm,uvfits
33,uvfits_norm/ER6_SGRA_2017_097_hi_hops_netcal-L...,NaN,NaN,uvfits,norm,97,hi,hops,norm,uvfits
34,uvfits_norm/ER6_SGRA_2017_097_lo_casa_netcal-L...,NaN,NaN,uvfits,norm,97,lo,casa,norm,uvfits
35,uvfits_norm/ER6_SGRA_2017_097_lo_hops_netcal-L...,NaN,NaN,uvfits,norm,97,lo,hops,norm,uvfits