A repository can now be created using the buil cli function. There are multiple ways to create the repo, first being directly entering the format strings

In [ ]:
from hallmark.repo_builder import build_repo

L1_datasets = {
    "EHTC_2017L1_May2022": [
        {"fmt": "{project_code}/group.uid{guid}.{author}.{kind}.{format}",
         "db": "description.tsv"},
        {"fmt":
         "{eht_project_code}/group.uid{guid}.{author}.{scope}-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".{prefix}track{track}-{date}.app_deliverables.{format}",
         "db": "deliverables.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.{track}-{alma_band}-"
        "{eht_project_code}/group.uid{guid}.{author}.{track}-{alma_band}-",
         "db": "data.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.metadata-"
         "{eht_product_code}.{format}",
         "db": "meta.tsv"},
        {"name": "checksum",
         "fmt": "{eht_project_code}.{algorithm}sums",
         "db": "checksums.tsv"}
         ],
    "EHTC_2018L1_Dec2024": [
        {"fmt":
         "{project_date}/{project_code}/group.uid{guid}.{author}.{kind}.{format}",
         "db": "description.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.{track}"
         "-{obs_num}-{band}-{pointing}-{source}-{kind}.{format}",
         "db": "data.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.{scope}"
         "-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".{prefix}track{track}-{date}.app_deliverables.{format}",
         "db": "deliverables.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}.metadata-"
         "{meta_id}.{format}",
         "db": "meta.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".EHTmetadata_{meta_id}.{format}",
         "db": "meta.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/{source}-v{version}-{kind}.{format}",
         "db": "Oct2018.tsv"},
        {"fmt":
         "{project_date}/{eht_project_code}/group.uid{guid}.{author}.md5sum.{format}",
         "db": "checksums.tsv"},
        {"fmt": "{project_date}/{eht_project_code}/group.uid{guid}.{author}"
         ".readme-metadata-update-v{old_version}-to-v{new_version}.{format}",
         "db": "readme_updates.tsv"}],
    "EHTC_2021L1_Dec2025": [
        {"fmt": "{project_code}/group.uid{guid}.{author}.{kind}.{format}",
         "db": "description.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.{track}-{obs_num}-{band}"
         "-{pointing}-{source}-{kind}.{format}",
         "db": "data.tsv"},
        {"fmt":
         "{eht_project_code}/group.uid{guid}.{author}.{scope}-processing-logs.{format}",
         "db": "log.tsv"},
        {"fmt":
         "{eht_project_code}/group.uid{guid}.{author}.metadata-{meta_id}.{meta_ext}",
         "db": "meta.tsv"},
        {"fmt": "{eht_project_code}/group.uid{guid}.{author}.md5sum.{format}",
         "db": "checksums.tsv"},]
}
dataset_names = list(L1_datasets.keys())
L1_idx = 2
dataset_name = dataset_names[L1_idx]

repo = build_repo(
    repo_path=f"/home/samj98/hallmark_demo_outputs/{dataset_name}.hm",
    dataset_name=dataset_name,
    #fmt_entries=L1_datasets[dataset_name],
    remotes=[{"name": "origin"}])

In [ ]:
import pandas as pd
from IPython.display import display

print("=== config.yml ===")
print((repo.dothm.path / "config.yml").read_text())

for tsv_path in sorted(repo.dothm.path.glob("*.tsv")):
    print(f"=== {tsv_path.name} ===")
    df = pd.read_csv(tsv_path, sep="\t")
    display(df)

In [ ]:
from hallmark.repo_builder import build_repo

L2_dataset_names = ["EHTC_CenA2017_Jul2021", "EHTC_First3C279Results_May2020",
                    "EHTC_FirstM87Results_Apr2019", "EHTC_FirstSgrAPol_Mar2024",
                    "EHTC_FirstSgrAResults_May2022", "EHTC_M87-2018_Mar2024",
                    "EHTC_M87mwl2017_Apr2021", "EHTC_M87mwl2018_Dec2024",
                    "EHTC_M87pol2017_Nov2023", "EHTC_metadata2018_Dec2023",
                    "EHTC_MonitoringM87_Sep2020", "EHTC_SgrAmwl2017_May2022"]
L2_idx = 9
L2_dataset_name = L2_dataset_names[L2_idx]

repo_no_fmts = build_repo(
    repo_path=f"/home/samj98/hallmark_outputs/{L2_dataset_name}.hm",
    dataset_name=L2_dataset_name,
    fmt_entries=None,
    remotes=[{"name": "origin"}])

Listing remote files for 'EHTC_metadata2018_Dec2023'...
Found 393 files in 18.2s
Matching 393 files against 11 fmt(s)...
Progress: 0/393 files matched so far
Progress: 100/393 files matched so far
Progress: 200/393 files matched so far
Progress: 300/393 files matched so far

In [5]:
import pandas as pd
from IPython.display import display

print("=== config.yml ===")
print((repo_no_fmts.dothm.path / "config.yml").read_text())

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
):
    for tsv_path in sorted(repo_no_fmts.dothm.path.glob("*.tsv")):
        print(f"=== {tsv_path.name} ===")
        df = pd.read_csv(tsv_path, sep="\t")
        display(df)

=== config.yml ===
data:
- name: inventory
  file: INVENTORY.txt
  md5: 6e953f6e21633348a23a4314a9cac6ff
- name: license
  file: LICENSE.txt
  md5: 7177765c4d9d3ba7d74281362186c926
- name: readme
  file: README.pdf
  md5: 6aa77bbcca695b1e69ad15b8f9dd1597
- name: readme
  file: antab/README
  md5: b598ca965d49d714eb7e5fca571428c2
- name: readme
  file: aux/README
  md5: 7789737b5f4a6506d94cb86f9f426086
- name: readme
  file: plots/README
  md5: b10e9ee1d55ec4ba8a8b247c4f775935
- name: readme
  file: raw/EHT2018_metadata_PV/DPFU+GainCurve/README
  md5: 87fa0a73b6e8a7958b22d61553c2c075
- name: readme
  file: raw/EHT2018_metadata_PV/Tsys_tables/README
  md5: 1a6e2a8fcdcbe67e78da94ef6bbc1454
- fmt: aux/{auxiliary_name}.{format}
  db: auxiliary.tsv
- fmt: antab/{processing_state}/{experiment}_{band}_{processing_variant}.AN
  db: antab.tsv
- fmt: plots/{station}_{measurement}_{frequency_epoch}.html
  db: plots.tsv
- fmt: plots/plots_{station_group}/{station}_{measurement}_{axis}_{experiment}-{band}.png
  db: plots.tsv
- fmt: plots/{station}_tsys_{comparison}.png
  db: plots.tsv
- fmt: plots/EHT2018_{measurement}_{axis}_{frequency}.png
  db: plots.tsv
- fmt: plots/{station}_EHT2018_{measurement}_{axis}_{frequency}.png
  db: plots.tsv
- fmt: raw/EHT2018_metadata_{station_group}/e18{experiment_id}_{station_code}.{metadata_type}
  db: raw.tsv
- fmt: raw/EHT2018_metadata_AA/{experiment}_{band}_AA.tsys
  db: raw.tsv
- fmt: raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/{experiment}_{band}_AA_PC.ANTAB
  db: raw.tsv
- fmt: raw/EHT2018_metadata_{station}/{metadata_path}
  db: raw.tsv
remote:
- name: origin
  url: https://data.cyverse.org/dav-anon/iplant/commons/cyverse_curated/EHTC_metadata2018_Dec2023/

=== antab.tsv ===

,path,checksum_algorithm,checksum,processing_state,experiment,band,processing_variant
0,antab/processed/e18a24_b1_proc.AN,NaN,NaN,processed,e18a24,b1,proc
1,antab/processed/e18a24_b2_proc.AN,NaN,NaN,processed,e18a24,b2,proc
2,antab/processed/e18a24_b3_proc.AN,NaN,NaN,processed,e18a24,b3,proc
3,antab/processed/e18a24_b4_proc.AN,NaN,NaN,processed,e18a24,b4,proc
4,antab/processed/e18c21_b1_proc.AN,NaN,NaN,processed,e18c21,b1,proc
5,antab/processed/e18c21_b2_proc.AN,NaN,NaN,processed,e18c21,b2,proc
6,antab/processed/e18c21_b3_proc.AN,NaN,NaN,processed,e18c21,b3,proc
7,antab/processed/e18c21_b4_proc.AN,NaN,NaN,processed,e18c21,b4,proc
8,antab/processed/e18c25_b1_proc.AN,NaN,NaN,processed,e18c25,b1,proc
9,antab/processed/e18c25_b1_proc_fixAX.AN,NaN,NaN,processed,e18c25,b1,proc_fixAX
10,antab/processed/e18c25_b2_proc.AN,NaN,NaN,processed,e18c25,b2,proc
11,antab/processed/e18c25_b2_proc_fixAX.AN,NaN,NaN,processed,e18c25,b2,proc_fixAX
12,antab/processed/e18c25_b3_proc.AN,NaN,NaN,processed,e18c25,b3,proc
13,antab/processed/e18c25_b3_proc_fixAX.AN,NaN,NaN,processed,e18c25,b3,proc_fixAX
14,antab/processed/e18c25_b4_proc.AN,NaN,NaN,processed,e18c25,b4,proc
15,antab/processed/e18c25_b4_proc_fixAX.AN,NaN,NaN,processed,e18c25,b4,proc_fixAX
16,antab/processed/e18d28_b1_proc.AN,NaN,NaN,processed,e18d28,b1,proc
17,antab/processed/e18d28_b2_proc.AN,NaN,NaN,processed,e18d28,b2,proc
18,antab/processed/e18d28_b3_proc.AN,NaN,NaN,processed,e18d28,b3,proc
19,antab/processed/e18d28_b4_proc.AN,NaN,NaN,processed,e18d28,b4,proc
20,antab/processed/e18e22_b1_proc.AN,NaN,NaN,processed,e18e22,b1,proc
21,antab/processed/e18e22_b2_proc.AN,NaN,NaN,processed,e18e22,b2,proc
22,antab/processed/e18e22_b3_proc.AN,NaN,NaN,processed,e18e22,b3,proc
23,antab/processed/e18e22_b4_proc.AN,NaN,NaN,processed,e18e22,b4,proc
24,antab/processed/e18g27_b1_proc.AN,NaN,NaN,processed,e18g27,b1,proc
25,antab/processed/e18g27_b2_proc.AN,NaN,NaN,processed,e18g27,b2,proc
26,antab/processed/e18g27_b3_proc.AN,NaN,NaN,processed,e18g27,b3,proc
27,antab/processed/e18g27_b4_proc.AN,NaN,NaN,processed,e18g27,b4,proc
28,antab/raw/e18a24_b1_raw.AN,NaN,NaN,raw,e18a24,b1,raw
29,antab/raw/e18a24_b2_raw.AN,NaN,NaN,raw,e18a24,b2,raw
30,antab/raw/e18a24_b3_raw.AN,NaN,NaN,raw,e18a24,b3,raw
31,antab/raw/e18a24_b4_raw.AN,NaN,NaN,raw,e18a24,b4,raw
32,antab/raw/e18c21_b1_raw.AN,NaN,NaN,raw,e18c21,b1,raw
33,antab/raw/e18c21_b2_raw.AN,NaN,NaN,raw,e18c21,b2,raw
34,antab/raw/e18c21_b3_raw.AN,NaN,NaN,raw,e18c21,b3,raw
35,antab/raw/e18c21_b4_raw.AN,NaN,NaN,raw,e18c21,b4,raw
36,antab/raw/e18c25_b1_raw.AN,NaN,NaN,raw,e18c25,b1,raw
37,antab/raw/e18c25_b2_raw.AN,NaN,NaN,raw,e18c25,b2,raw
38,antab/raw/e18c25_b3_raw.AN,NaN,NaN,raw,e18c25,b3,raw
39,antab/raw/e18c25_b4_raw.AN,NaN,NaN,raw,e18c25,b4,raw
40,antab/raw/e18d28_b1_raw.AN,NaN,NaN,raw,e18d28,b1,raw
41,antab/raw/e18d28_b2_raw.AN,NaN,NaN,raw,e18d28,b2,raw
42,antab/raw/e18d28_b3_raw.AN,NaN,NaN,raw,e18d28,b3,raw
43,antab/raw/e18d28_b4_raw.AN,NaN,NaN,raw,e18d28,b4,raw
44,antab/raw/e18e22_b1_raw.AN,NaN,NaN,raw,e18e22,b1,raw
45,antab/raw/e18e22_b2_raw.AN,NaN,NaN,raw,e18e22,b2,raw
46,antab/raw/e18e22_b3_raw.AN,NaN,NaN,raw,e18e22,b3,raw
47,antab/raw/e18e22_b4_raw.AN,NaN,NaN,raw,e18e22,b4,raw
48,antab/raw/e18g27_b1_raw.AN,NaN,NaN,raw,e18g27,b1,raw
49,antab/raw/e18g27_b2_raw.AN,NaN,NaN,raw,e18g27,b2,raw
50,antab/raw/e18g27_b3_raw.AN,NaN,NaN,raw,e18g27,b3,raw
51,antab/raw/e18g27_b4_raw.AN,NaN,NaN,raw,e18g27,b4,raw

=== auxiliary.tsv ===

,path,checksum_algorithm,checksum,auxiliary_name,format
0,aux/AZ2Z.txt,NaN,NaN,AZ2Z,txt
1,aux/SMT2Z.txt,NaN,NaN,SMT2Z,txt
2,aux/Z2AZ.txt,NaN,NaN,Z2AZ,txt
3,aux/Z2SMT.txt,NaN,NaN,Z2SMT,txt
4,aux/antL.txt,NaN,NaN,antL,txt
5,aux/ant_locat.txt,NaN,NaN,ant_locat,txt
6,aux/deleted_df.tab,NaN,NaN,deleted_df,tab
7,aux/elev_diff.tab,NaN,NaN,elev_diff,tab
8,aux/expt2track.txt,NaN,NaN,expt2track,txt
9,aux/exptL0.txt,NaN,NaN,exptL0,txt
10,aux/modify_df.tab,NaN,NaN,modify_df,tab
11,aux/opt_thick_scans.tab,NaN,NaN,opt_thick_scans,tab
12,aux/sefd_proc.tab,NaN,NaN,sefd_proc,tab
13,aux/sourL.txt,NaN,NaN,sourL,txt
14,aux/station_dic.txt,NaN,NaN,station_dic,txt
15,aux/track2expt.txt,NaN,NaN,track2expt,txt
16,aux/tsa.dict,NaN,NaN,tsa,dict
17,aux/tsys_proc.tab,NaN,NaN,tsys_proc,tab
18,aux/tsystime_dupl.tab,NaN,NaN,tsystime_dupl,tab
19,aux/vexflag_info.tab,NaN,NaN,vexflag_info,tab
20,aux/vtf_elev_check.tab,NaN,NaN,vtf_elev_check,tab
21,aux/vtf_raw.tab,NaN,NaN,vtf_raw,tab

=== data.tsv ===

Empty DataFrame
Columns: [sha1]
Index: []

=== plots.tsv ===

,path,checksum_algorithm,checksum,station,measurement,frequency_epoch,station_group,axis,experiment,band,comparison,frequency
0,plots/Ax_TsysL_230ghz2018.html,NaN,NaN,Ax,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
1,plots/Ax_TsysR_230ghz2018.html,NaN,NaN,Ax,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
2,plots/Gl_TsysL_230ghz2018.html,NaN,NaN,Gl,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
3,plots/Gl_TsysR_230ghz2018.html,NaN,NaN,Gl,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
4,plots/Lm_TsysL_230ghz2018.html,NaN,NaN,Lm,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
5,plots/Lm_TsysR_230ghz2018.html,NaN,NaN,Lm,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
6,plots/Mg_TsysL_230ghz2018.html,NaN,NaN,Mg,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
7,plots/Mg_TsysR_230ghz2018.html,NaN,NaN,Mg,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
8,plots/Mm_TsysR_230ghz2018.html,NaN,NaN,Mm,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
9,plots/Pv_TsysL_230ghz2018.html,NaN,NaN,Pv,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
10,plots/Pv_TsysR_230ghz2018.html,NaN,NaN,Pv,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
11,plots/Sw_SEFDL_230ghz2018.html,NaN,NaN,Sw,SEFDL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
12,plots/Sw_SEFDR_230ghz2018.html,NaN,NaN,Sw,SEFDR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
13,plots/Sz_TsysL_230ghz2018.html,NaN,NaN,Sz,TsysL,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
14,plots/Sz_TsysR_230ghz2018.html,NaN,NaN,Sz,TsysR,230ghz2018,NaN,NaN,NaN,NaN,NaN,NaN
15,plots/plots_Aa/Aa_tsyspeff_time_e18a24-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18a24,b1,NaN,NaN
16,plots/plots_Aa/Aa_tsyspeff_time_e18a24-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18a24,b2,NaN,NaN
17,plots/plots_Aa/Aa_tsyspeff_time_e18a24-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18a24,b3,NaN,NaN
18,plots/plots_Aa/Aa_tsyspeff_time_e18a24-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18a24,b4,NaN,NaN
19,plots/plots_Aa/Aa_tsyspeff_time_e18c21-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c21,b1,NaN,NaN
20,plots/plots_Aa/Aa_tsyspeff_time_e18c21-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c21,b2,NaN,NaN
21,plots/plots_Aa/Aa_tsyspeff_time_e18c21-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c21,b3,NaN,NaN
22,plots/plots_Aa/Aa_tsyspeff_time_e18c21-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c21,b4,NaN,NaN
23,plots/plots_Aa/Aa_tsyspeff_time_e18c25-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c25,b1,NaN,NaN
24,plots/plots_Aa/Aa_tsyspeff_time_e18c25-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c25,b2,NaN,NaN
25,plots/plots_Aa/Aa_tsyspeff_time_e18c25-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c25,b3,NaN,NaN
26,plots/plots_Aa/Aa_tsyspeff_time_e18c25-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18c25,b4,NaN,NaN
27,plots/plots_Aa/Aa_tsyspeff_time_e18d28-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18d28,b1,NaN,NaN
28,plots/plots_Aa/Aa_tsyspeff_time_e18d28-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18d28,b2,NaN,NaN
29,plots/plots_Aa/Aa_tsyspeff_time_e18d28-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18d28,b3,NaN,NaN
30,plots/plots_Aa/Aa_tsyspeff_time_e18d28-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18d28,b4,NaN,NaN
31,plots/plots_Aa/Aa_tsyspeff_time_e18e22-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18e22,b1,NaN,NaN
32,plots/plots_Aa/Aa_tsyspeff_time_e18e22-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18e22,b2,NaN,NaN
33,plots/plots_Aa/Aa_tsyspeff_time_e18e22-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18e22,b3,NaN,NaN
34,plots/plots_Aa/Aa_tsyspeff_time_e18e22-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18e22,b4,NaN,NaN
35,plots/plots_Aa/Aa_tsyspeff_time_e18g27-b1.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18g27,b1,NaN,NaN
36,plots/plots_Aa/Aa_tsyspeff_time_e18g27-b2.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18g27,b2,NaN,NaN
37,plots/plots_Aa/Aa_tsyspeff_time_e18g27-b3.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18g27,b3,NaN,NaN
38,plots/plots_Aa/Aa_tsyspeff_time_e18g27-b4.png,NaN,NaN,Aa,tsyspeff,NaN,Aa,time,e18g27,b4,NaN,NaN
39,plots/plots_Sw/Sw_pheff_e18a24.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18a24,NaN,NaN,NaN
40,plots/plots_Sw/Sw_pheff_e18c21.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18c21,NaN,NaN,NaN
41,plots/plots_Sw/Sw_pheff_e18c25.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18c25,NaN,NaN,NaN
42,plots/plots_Sw/Sw_pheff_e18d28.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18d28,NaN,NaN,NaN
43,plots/plots_Sw/Sw_pheff_e18e22.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18e22,NaN,NaN,NaN
44,plots/plots_Sw/Sw_pheff_e18g27.png,NaN,NaN,Sw,NaN,NaN,Sw,pheff,e18g27,NaN,NaN,NaN
45,plots/plots_Sw/Sw_sefd_time_e18a24.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18a24,NaN,NaN,NaN
46,plots/plots_Sw/Sw_sefd_time_e18c21.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18c21,NaN,NaN,NaN
47,plots/plots_Sw/Sw_sefd_time_e18c25.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18c25,NaN,NaN,NaN
48,plots/plots_Sw/Sw_sefd_time_e18d28.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18d28,NaN,NaN,NaN
49,plots/plots_Sw/Sw_sefd_time_e18e22.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18e22,NaN,NaN,NaN
50,plots/plots_Sw/Sw_sefd_time_e18g27.png,NaN,NaN,Sw,sefd,NaN,Sw,time,e18g27,NaN,NaN,NaN
51,plots/plots_Sw/Sw_tsys_elev_e18a24.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18a24,NaN,NaN,NaN
52,plots/plots_Sw/Sw_tsys_elev_e18c21.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18c21,NaN,NaN,NaN
53,plots/plots_Sw/Sw_tsys_elev_e18c25.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18c25,NaN,NaN,NaN
54,plots/plots_Sw/Sw_tsys_elev_e18d28.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18d28,NaN,NaN,NaN
55,plots/plots_Sw/Sw_tsys_elev_e18e22.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18e22,NaN,NaN,NaN
56,plots/plots_Sw/Sw_tsys_elev_e18g27.png,NaN,NaN,Sw,tsys,NaN,Sw,elev,e18g27,NaN,NaN,NaN
57,plots/plots_Sw/Sw_tsys_time_e18a24.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18a24,NaN,NaN,NaN
58,plots/plots_Sw/Sw_tsys_time_e18c21.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18c21,NaN,NaN,NaN
59,plots/plots_Sw/Sw_tsys_time_e18c25.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18c25,NaN,NaN,NaN
60,plots/plots_Sw/Sw_tsys_time_e18d28.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18d28,NaN,NaN,NaN
61,plots/plots_Sw/Sw_tsys_time_e18e22.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18e22,NaN,NaN,NaN
62,plots/plots_Sw/Sw_tsys_time_e18g27.png,NaN,NaN,Sw,tsys,NaN,Sw,time,e18g27,NaN,NaN,NaN
63,plots/Ax_tsys_comp.png,NaN,NaN,Ax,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
64,plots/Ax_tsys_elev_comp.png,NaN,NaN,Ax,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
65,plots/Gl_tsys_comp.png,NaN,NaN,Gl,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
66,plots/Gl_tsys_elev_comp.png,NaN,NaN,Gl,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
67,plots/Lm_tsys_comp.png,NaN,NaN,Lm,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
68,plots/Lm_tsys_elev_comp.png,NaN,NaN,Lm,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
69,plots/Mg_tsys_comp.png,NaN,NaN,Mg,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
70,plots/Mg_tsys_elev_comp.png,NaN,NaN,Mg,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
71,plots/Mm_tsys_comp.png,NaN,NaN,Mm,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
72,plots/Mm_tsys_elev_comp.png,NaN,NaN,Mm,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
73,plots/Pv_tsys_comp.png,NaN,NaN,Pv,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
74,plots/Pv_tsys_elev_comp.png,NaN,NaN,Pv,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
75,plots/Sz_tsys_comp.png,NaN,NaN,Sz,NaN,NaN,NaN,NaN,NaN,NaN,comp,NaN
76,plots/Sz_tsys_elev_comp.png,NaN,NaN,Sz,NaN,NaN,NaN,NaN,NaN,NaN,elev_comp,NaN
77,plots/EHT2018_tau_time_230ghz.png,NaN,NaN,NaN,tau,NaN,NaN,time,NaN,NaN,NaN,230ghz
78,plots/EHT2018_tsys_elev_230ghz.png,NaN,NaN,NaN,tsys,NaN,NaN,elev,NaN,NaN,NaN,230ghz
79,plots/EHT2018_tsys_time_230ghz.png,NaN,NaN,NaN,tsys,NaN,NaN,time,NaN,NaN,NaN,230ghz
80,plots/Sw_EHT2018_SEFD_elev_230ghz.png,NaN,NaN,Sw,SEFD,NaN,NaN,elev,NaN,NaN,NaN,230ghz

=== raw.tsv ===

,path,checksum_algorithm,checksum,station_group,experiment_id,station_code,metadata_type,experiment,band,station,metadata_path
0,raw/EHT2018_metadata_AA/e18a24_AA.flag,NaN,NaN,AA,a24,AA,flag,NaN,NaN,NaN,NaN
1,raw/EHT2018_metadata_AA/e18a24_AA.pheff,NaN,NaN,AA,a24,AA,pheff,NaN,NaN,NaN,NaN
2,raw/EHT2018_metadata_AA/e18c21_AA.flag,NaN,NaN,AA,c21,AA,flag,NaN,NaN,NaN,NaN
3,raw/EHT2018_metadata_AA/e18c21_AA.pheff,NaN,NaN,AA,c21,AA,pheff,NaN,NaN,NaN,NaN
4,raw/EHT2018_metadata_AA/e18c25_AA.flag,NaN,NaN,AA,c25,AA,flag,NaN,NaN,NaN,NaN
5,raw/EHT2018_metadata_AA/e18c25_AA.pheff,NaN,NaN,AA,c25,AA,pheff,NaN,NaN,NaN,NaN
6,raw/EHT2018_metadata_AA/e18d28_AA.flag,NaN,NaN,AA,d28,AA,flag,NaN,NaN,NaN,NaN
7,raw/EHT2018_metadata_AA/e18d28_AA.pheff,NaN,NaN,AA,d28,AA,pheff,NaN,NaN,NaN,NaN
8,raw/EHT2018_metadata_AA/e18e22_AA.flag,NaN,NaN,AA,e22,AA,flag,NaN,NaN,NaN,NaN
9,raw/EHT2018_metadata_AA/e18e22_AA.pheff,NaN,NaN,AA,e22,AA,pheff,NaN,NaN,NaN,NaN
10,raw/EHT2018_metadata_AA/e18g27_AA.flag,NaN,NaN,AA,g27,AA,flag,NaN,NaN,NaN,NaN
11,raw/EHT2018_metadata_AA/e18g27_AA.pheff,NaN,NaN,AA,g27,AA,pheff,NaN,NaN,NaN,NaN
12,raw/EHT2018_metadata_AX/e18a24_AX.flag,NaN,NaN,AX,a24,AX,flag,NaN,NaN,NaN,NaN
13,raw/EHT2018_metadata_AX/e18a24_AX.tsys,NaN,NaN,AX,a24,AX,tsys,NaN,NaN,NaN,NaN
14,raw/EHT2018_metadata_AX/e18c21_AX.flag,NaN,NaN,AX,c21,AX,flag,NaN,NaN,NaN,NaN
15,raw/EHT2018_metadata_AX/e18c21_AX.tsys,NaN,NaN,AX,c21,AX,tsys,NaN,NaN,NaN,NaN
16,raw/EHT2018_metadata_AX/e18c25_AX.flag,NaN,NaN,AX,c25,AX,flag,NaN,NaN,NaN,NaN
17,raw/EHT2018_metadata_AX/e18c25_AX.tsys,NaN,NaN,AX,c25,AX,tsys,NaN,NaN,NaN,NaN
18,raw/EHT2018_metadata_AX/e18e22_AX.flag,NaN,NaN,AX,e22,AX,flag,NaN,NaN,NaN,NaN
19,raw/EHT2018_metadata_AX/e18e22_AX.tsys,NaN,NaN,AX,e22,AX,tsys,NaN,NaN,NaN,NaN
20,raw/EHT2018_metadata_GL/e18c21_GL.flag,NaN,NaN,GL,c21,GL,flag,NaN,NaN,NaN,NaN
21,raw/EHT2018_metadata_GL/e18c21_GL.tsys,NaN,NaN,GL,c21,GL,tsys,NaN,NaN,NaN,NaN
22,raw/EHT2018_metadata_GL/e18c25_GL.flag,NaN,NaN,GL,c25,GL,flag,NaN,NaN,NaN,NaN
23,raw/EHT2018_metadata_GL/e18c25_GL.tsys,NaN,NaN,GL,c25,GL,tsys,NaN,NaN,NaN,NaN
24,raw/EHT2018_metadata_GL/e18d28_GL.flag,NaN,NaN,GL,d28,GL,flag,NaN,NaN,NaN,NaN
25,raw/EHT2018_metadata_GL/e18d28_GL.tsys,NaN,NaN,GL,d28,GL,tsys,NaN,NaN,NaN,NaN
26,raw/EHT2018_metadata_GL/e18e22_GL.flag,NaN,NaN,GL,e22,GL,flag,NaN,NaN,NaN,NaN
27,raw/EHT2018_metadata_GL/e18e22_GL.tsys,NaN,NaN,GL,e22,GL,tsys,NaN,NaN,NaN,NaN
28,raw/EHT2018_metadata_GL/e18g27_GL.flag,NaN,NaN,GL,g27,GL,flag,NaN,NaN,NaN,NaN
29,raw/EHT2018_metadata_GL/e18g27_GL.tsys,NaN,NaN,GL,g27,GL,tsys,NaN,NaN,NaN,NaN
30,raw/EHT2018_metadata_LM/e18a24_LM.flag,NaN,NaN,LM,a24,LM,flag,NaN,NaN,NaN,NaN
31,raw/EHT2018_metadata_LM/e18a24_LM.tsys,NaN,NaN,LM,a24,LM,tsys,NaN,NaN,NaN,NaN
32,raw/EHT2018_metadata_LM/e18c21_LM.flag,NaN,NaN,LM,c21,LM,flag,NaN,NaN,NaN,NaN
33,raw/EHT2018_metadata_LM/e18c21_LM.tsys,NaN,NaN,LM,c21,LM,tsys,NaN,NaN,NaN,NaN
34,raw/EHT2018_metadata_LM/e18e22_LM.flag,NaN,NaN,LM,e22,LM,flag,NaN,NaN,NaN,NaN
35,raw/EHT2018_metadata_LM/e18e22_LM.tsys,NaN,NaN,LM,e22,LM,tsys,NaN,NaN,NaN,NaN
36,raw/EHT2018_metadata_MG/e18a24_MG.flag,NaN,NaN,MG,a24,MG,flag,NaN,NaN,NaN,NaN
37,raw/EHT2018_metadata_MG/e18a24_MG.tsys,NaN,NaN,MG,a24,MG,tsys,NaN,NaN,NaN,NaN
38,raw/EHT2018_metadata_MG/e18c21_MG.flag,NaN,NaN,MG,c21,MG,flag,NaN,NaN,NaN,NaN
39,raw/EHT2018_metadata_MG/e18c21_MG.tsys,NaN,NaN,MG,c21,MG,tsys,NaN,NaN,NaN,NaN
40,raw/EHT2018_metadata_MG/e18c25_MG.flag,NaN,NaN,MG,c25,MG,flag,NaN,NaN,NaN,NaN
41,raw/EHT2018_metadata_MG/e18c25_MG.tsys,NaN,NaN,MG,c25,MG,tsys,NaN,NaN,NaN,NaN
42,raw/EHT2018_metadata_MG/e18d28_MG.flag,NaN,NaN,MG,d28,MG,flag,NaN,NaN,NaN,NaN
43,raw/EHT2018_metadata_MG/e18d28_MG.tsys,NaN,NaN,MG,d28,MG,tsys,NaN,NaN,NaN,NaN
44,raw/EHT2018_metadata_MG/e18e22_MG.flag,NaN,NaN,MG,e22,MG,flag,NaN,NaN,NaN,NaN
45,raw/EHT2018_metadata_MG/e18e22_MG.tsys,NaN,NaN,MG,e22,MG,tsys,NaN,NaN,NaN,NaN
46,raw/EHT2018_metadata_MG/e18g27_MG.flag,NaN,NaN,MG,g27,MG,flag,NaN,NaN,NaN,NaN
47,raw/EHT2018_metadata_MG/e18g27_MG.tsys,NaN,NaN,MG,g27,MG,tsys,NaN,NaN,NaN,NaN
48,raw/EHT2018_metadata_MM/e18a24_Mm.flag,NaN,NaN,MM,a24,Mm,flag,NaN,NaN,NaN,NaN
49,raw/EHT2018_metadata_MM/e18a24_Mm.tsys,NaN,NaN,MM,a24,Mm,tsys,NaN,NaN,NaN,NaN
50,raw/EHT2018_metadata_MM/e18c21_Mm.flag,NaN,NaN,MM,c21,Mm,flag,NaN,NaN,NaN,NaN
51,raw/EHT2018_metadata_MM/e18c21_Mm.tsys,NaN,NaN,MM,c21,Mm,tsys,NaN,NaN,NaN,NaN
52,raw/EHT2018_metadata_MM/e18c25_Mm.flag,NaN,NaN,MM,c25,Mm,flag,NaN,NaN,NaN,NaN
53,raw/EHT2018_metadata_MM/e18c25_Mm.tsys,NaN,NaN,MM,c25,Mm,tsys,NaN,NaN,NaN,NaN
54,raw/EHT2018_metadata_MM/e18d28_Mm.flag,NaN,NaN,MM,d28,Mm,flag,NaN,NaN,NaN,NaN
55,raw/EHT2018_metadata_MM/e18d28_Mm.tsys,NaN,NaN,MM,d28,Mm,tsys,NaN,NaN,NaN,NaN
56,raw/EHT2018_metadata_MM/e18e22_Mm.flag,NaN,NaN,MM,e22,Mm,flag,NaN,NaN,NaN,NaN
57,raw/EHT2018_metadata_MM/e18e22_Mm.tsys,NaN,NaN,MM,e22,Mm,tsys,NaN,NaN,NaN,NaN
58,raw/EHT2018_metadata_MM/e18g27_Mm.flag,NaN,NaN,MM,g27,Mm,flag,NaN,NaN,NaN,NaN
59,raw/EHT2018_metadata_MM/e18g27_Mm.tsys,NaN,NaN,MM,g27,Mm,tsys,NaN,NaN,NaN,NaN
60,raw/EHT2018_metadata_PV/Flag_tables/e18a24_Pv.flag,NaN,NaN,PV/Flag_tables,a24,Pv,flag,NaN,NaN,NaN,NaN
61,raw/EHT2018_metadata_PV/Flag_tables/e18c21_Pv.flag,NaN,NaN,PV/Flag_tables,c21,Pv,flag,NaN,NaN,NaN,NaN
62,raw/EHT2018_metadata_PV/Flag_tables/e18c25_Pv.flag,NaN,NaN,PV/Flag_tables,c25,Pv,flag,NaN,NaN,NaN,NaN
63,raw/EHT2018_metadata_PV/Flag_tables/e18d28_Pv.flag,NaN,NaN,PV/Flag_tables,d28,Pv,flag,NaN,NaN,NaN,NaN
64,raw/EHT2018_metadata_PV/Flag_tables/e18e22_Pv.flag,NaN,NaN,PV/Flag_tables,e22,Pv,flag,NaN,NaN,NaN,NaN
65,raw/EHT2018_metadata_PV/Flag_tables/e18g27_Pv.flag,NaN,NaN,PV/Flag_tables,g27,Pv,flag,NaN,NaN,NaN,NaN
66,raw/EHT2018_metadata_PV/Tsys_tables/e18a24_Pv.tsys,NaN,NaN,PV/Tsys_tables,a24,Pv,tsys,NaN,NaN,NaN,NaN
67,raw/EHT2018_metadata_PV/Tsys_tables/e18c21_Pv.tsys,NaN,NaN,PV/Tsys_tables,c21,Pv,tsys,NaN,NaN,NaN,NaN
68,raw/EHT2018_metadata_PV/Tsys_tables/e18c25_Pv.tsys,NaN,NaN,PV/Tsys_tables,c25,Pv,tsys,NaN,NaN,NaN,NaN
69,raw/EHT2018_metadata_PV/Tsys_tables/e18d28_Pv.tsys,NaN,NaN,PV/Tsys_tables,d28,Pv,tsys,NaN,NaN,NaN,NaN
70,raw/EHT2018_metadata_PV/Tsys_tables/e18g27_Pv.tsys,NaN,NaN,PV/Tsys_tables,g27,Pv,tsys,NaN,NaN,NaN,NaN
71,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18a24_CALs_Pv.txt,NaN,NaN,PV/Tsys_tables/supporting,a24,CALs_Pv,txt,NaN,NaN,NaN,NaN
72,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18a24pv.wx,NaN,NaN,PV/Tsys_tables/supporting,a24pv,NaN,wx,NaN,NaN,NaN,NaN
73,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18c21_CALs_Pv.txt,NaN,NaN,PV/Tsys_tables/supporting,c21,CALs_Pv,txt,NaN,NaN,NaN,NaN
74,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18c21pv.wx,NaN,NaN,PV/Tsys_tables/supporting,c21pv,NaN,wx,NaN,NaN,NaN,NaN
75,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18c25_CALs_Pv.txt,NaN,NaN,PV/Tsys_tables/supporting,c25,CALs_Pv,txt,NaN,NaN,NaN,NaN
76,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18c25pv.wx,NaN,NaN,PV/Tsys_tables/supporting,c25pv,NaN,wx,NaN,NaN,NaN,NaN
77,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18d28_CALs_Pv.txt,NaN,NaN,PV/Tsys_tables/supporting,d28,CALs_Pv,txt,NaN,NaN,NaN,NaN
78,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18d28pv.wx,NaN,NaN,PV/Tsys_tables/supporting,d28pv,NaN,wx,NaN,NaN,NaN,NaN
79,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18g27_CALs_Pv.txt,NaN,NaN,PV/Tsys_tables/supporting,g27,CALs_Pv,txt,NaN,NaN,NaN,NaN
80,raw/EHT2018_metadata_PV/Tsys_tables/supporting/e18g27pv.wx,NaN,NaN,PV/Tsys_tables/supporting,g27pv,NaN,wx,NaN,NaN,NaN,NaN
81,raw/EHT2018_metadata_SW/e18a24_SW.flag,NaN,NaN,SW,a24,SW,flag,NaN,NaN,NaN,NaN
82,raw/EHT2018_metadata_SW/e18a24_SW.pheff,NaN,NaN,SW,a24,SW,pheff,NaN,NaN,NaN,NaN
83,raw/EHT2018_metadata_SW/e18a24_SW.tsys,NaN,NaN,SW,a24,SW,tsys,NaN,NaN,NaN,NaN
84,raw/EHT2018_metadata_SW/e18c21_SW.flag,NaN,NaN,SW,c21,SW,flag,NaN,NaN,NaN,NaN
85,raw/EHT2018_metadata_SW/e18c21_SW.pheff,NaN,NaN,SW,c21,SW,pheff,NaN,NaN,NaN,NaN
86,raw/EHT2018_metadata_SW/e18c21_SW.tsys,NaN,NaN,SW,c21,SW,tsys,NaN,NaN,NaN,NaN
87,raw/EHT2018_metadata_SW/e18c25_SW.flag,NaN,NaN,SW,c25,SW,flag,NaN,NaN,NaN,NaN
88,raw/EHT2018_metadata_SW/e18c25_SW.pheff,NaN,NaN,SW,c25,SW,pheff,NaN,NaN,NaN,NaN
89,raw/EHT2018_metadata_SW/e18c25_SW.tsys,NaN,NaN,SW,c25,SW,tsys,NaN,NaN,NaN,NaN
90,raw/EHT2018_metadata_SW/e18d28_SW.flag,NaN,NaN,SW,d28,SW,flag,NaN,NaN,NaN,NaN
91,raw/EHT2018_metadata_SW/e18d28_SW.pheff,NaN,NaN,SW,d28,SW,pheff,NaN,NaN,NaN,NaN
92,raw/EHT2018_metadata_SW/e18d28_SW.tsys,NaN,NaN,SW,d28,SW,tsys,NaN,NaN,NaN,NaN
93,raw/EHT2018_metadata_SW/e18e22_SW.flag,NaN,NaN,SW,e22,SW,flag,NaN,NaN,NaN,NaN
94,raw/EHT2018_metadata_SW/e18e22_SW.pheff,NaN,NaN,SW,e22,SW,pheff,NaN,NaN,NaN,NaN
95,raw/EHT2018_metadata_SW/e18e22_SW.tsys,NaN,NaN,SW,e22,SW,tsys,NaN,NaN,NaN,NaN
96,raw/EHT2018_metadata_SW/e18g27_SW.flag,NaN,NaN,SW,g27,SW,flag,NaN,NaN,NaN,NaN
97,raw/EHT2018_metadata_SW/e18g27_SW.pheff,NaN,NaN,SW,g27,SW,pheff,NaN,NaN,NaN,NaN
98,raw/EHT2018_metadata_SW/e18g27_SW.tsys,NaN,NaN,SW,g27,SW,tsys,NaN,NaN,NaN,NaN
99,raw/EHT2018_metadata_SZ/e18a24_SZ.flag,NaN,NaN,SZ,a24,SZ,flag,NaN,NaN,NaN,NaN
100,raw/EHT2018_metadata_SZ/e18a24_SZ.tsys,NaN,NaN,SZ,a24,SZ,tsys,NaN,NaN,NaN,NaN
101,raw/EHT2018_metadata_SZ/e18c21_SZ.flag,NaN,NaN,SZ,c21,SZ,flag,NaN,NaN,NaN,NaN
102,raw/EHT2018_metadata_SZ/e18c21_SZ.tsys,NaN,NaN,SZ,c21,SZ,tsys,NaN,NaN,NaN,NaN
103,raw/EHT2018_metadata_SZ/e18c25_SZ.flag,NaN,NaN,SZ,c25,SZ,flag,NaN,NaN,NaN,NaN
104,raw/EHT2018_metadata_SZ/e18c25_SZ.tsys,NaN,NaN,SZ,c25,SZ,tsys,NaN,NaN,NaN,NaN
105,raw/EHT2018_metadata_SZ/e18d28_SZ.flag,NaN,NaN,SZ,d28,SZ,flag,NaN,NaN,NaN,NaN
106,raw/EHT2018_metadata_SZ/e18d28_SZ.tsys,NaN,NaN,SZ,d28,SZ,tsys,NaN,NaN,NaN,NaN
107,raw/EHT2018_metadata_SZ/e18e22_SZ.flag,NaN,NaN,SZ,e22,SZ,flag,NaN,NaN,NaN,NaN
108,raw/EHT2018_metadata_SZ/e18e22_SZ.tsys,NaN,NaN,SZ,e22,SZ,tsys,NaN,NaN,NaN,NaN
109,raw/EHT2018_metadata_AA/e18a24_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b1,NaN,NaN
110,raw/EHT2018_metadata_AA/e18a24_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b2,NaN,NaN
111,raw/EHT2018_metadata_AA/e18a24_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b3,NaN,NaN
112,raw/EHT2018_metadata_AA/e18a24_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b4,NaN,NaN
113,raw/EHT2018_metadata_AA/e18c21_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b1,NaN,NaN
114,raw/EHT2018_metadata_AA/e18c21_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b2,NaN,NaN
115,raw/EHT2018_metadata_AA/e18c21_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b3,NaN,NaN
116,raw/EHT2018_metadata_AA/e18c21_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b4,NaN,NaN
117,raw/EHT2018_metadata_AA/e18c25_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b1,NaN,NaN
118,raw/EHT2018_metadata_AA/e18c25_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b2,NaN,NaN
119,raw/EHT2018_metadata_AA/e18c25_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b3,NaN,NaN
120,raw/EHT2018_metadata_AA/e18c25_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b4,NaN,NaN
121,raw/EHT2018_metadata_AA/e18d28_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b1,NaN,NaN
122,raw/EHT2018_metadata_AA/e18d28_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b2,NaN,NaN
123,raw/EHT2018_metadata_AA/e18d28_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b3,NaN,NaN
124,raw/EHT2018_metadata_AA/e18d28_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b4,NaN,NaN
125,raw/EHT2018_metadata_AA/e18e22_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b1,NaN,NaN
126,raw/EHT2018_metadata_AA/e18e22_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b2,NaN,NaN
127,raw/EHT2018_metadata_AA/e18e22_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b3,NaN,NaN
128,raw/EHT2018_metadata_AA/e18e22_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b4,NaN,NaN
129,raw/EHT2018_metadata_AA/e18g27_b1_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b1,NaN,NaN
130,raw/EHT2018_metadata_AA/e18g27_b2_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b2,NaN,NaN
131,raw/EHT2018_metadata_AA/e18g27_b3_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b3,NaN,NaN
132,raw/EHT2018_metadata_AA/e18g27_b4_AA.tsys,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b4,NaN,NaN
133,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18a24_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b1,NaN,NaN
134,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18a24_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b2,NaN,NaN
135,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18a24_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b3,NaN,NaN
136,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18a24_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18a24,b4,NaN,NaN
137,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c21_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b1,NaN,NaN
138,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c21_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b2,NaN,NaN
139,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c21_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b3,NaN,NaN
140,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c21_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c21,b4,NaN,NaN
141,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c25_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b1,NaN,NaN
142,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c25_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b2,NaN,NaN
143,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c25_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b3,NaN,NaN
144,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18c25_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18c25,b4,NaN,NaN
145,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18d28_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b1,NaN,NaN
146,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18d28_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b2,NaN,NaN
147,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18d28_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b3,NaN,NaN
148,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18d28_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18d28,b4,NaN,NaN
149,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18e22_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b1,NaN,NaN
150,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18e22_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b2,NaN,NaN
151,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18e22_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b3,NaN,NaN
152,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18e22_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18e22,b4,NaN,NaN
153,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18g27_b1_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b1,NaN,NaN
154,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18g27_b2_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b2,NaN,NaN
155,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18g27_b3_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b3,NaN,NaN
156,raw/EHT2018_metadata_AA/EHT2018_ANTAB_AA/e18g27_b4_AA_PC.ANTAB,NaN,NaN,NaN,NaN,NaN,NaN,e18g27,b4,NaN,NaN
157,raw/EHT2018_metadata_AX/APEX%20DPFU/ApexGain.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AX,APEX%20DPFU/ApexGain.pdf
158,raw/EHT2018_metadata_AX/APEX%20DPFU/Planet-All-Gain.v3.ods,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AX,APEX%20DPFU/Planet-All-Gain.v3.ods
159,raw/EHT2018_metadata_AX/APEX%20DPFU/gauss-fits.dat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AX,APEX%20DPFU/gauss-fits.dat
160,raw/EHT2018_metadata_GL/GL_2018-04.gc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GL,GL_2018-04.gc
161,raw/EHT2018_metadata_LM/LM_2020-01.gc.binned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LM,LM_2020-01.gc.binned
162,raw/EHT2018_metadata_MG/MG_2018-04_header.antab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MG,MG_2018-04_header.antab
163,raw/EHT2018_metadata_MG/efficiency%20measurements/MG_2018-04_Jupiter.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MG,efficiency%20measurements/MG_2018-04_Jupiter.txt
164,raw/EHT2018_metadata_MG/efficiency%20measurements/MG_2018-04_Mars.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MG,efficiency%20measurements/MG_2018-04_Mars.txt
165,raw/EHT2018_metadata_MG/efficiency%20measurements/MG_2018-04_Saturn.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MG,efficiency%20measurements/MG_2018-04_Saturn.txt
166,raw/EHT2018_metadata_MM/JCMT_2017/DPFU_fit_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/DPFU_fit_JCMT.png
167,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_DPFU.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_DPFU.png
168,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_DPFU.py,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_DPFU.py
169,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_eta_A.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_eta_A.png
170,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_fitparams.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_fitparams.txt
171,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/DPFU_fit_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/DPFU_fit_JCMT.png
172,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_efficiency_memo.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_efficiency_memo.pdf
173,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_eta_A.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_eta_A.png
174,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_fitparams.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_fitparams.txt
175,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo.aux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo.aux
176,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo.log,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo.log
177,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo.pdf
178,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo.synctex.gz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo.synctex.gz
179,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo.tex,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo.tex
180,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/JCMT_memo_remo_comments.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/JCMT_memo_remo_comments.pdf
181,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/aperture_efficiency_test.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/aperture_efficiency_test.png
182,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/cumulative_stats_residuals.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/cumulative_stats_residuals.png
183,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/eff_day.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/eff_day.png
184,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/etaA_fit_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/etaA_fit_JCMT.png
185,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/etaA_fits_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/etaA_fits_JCMT.png
186,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/histogram_etaA_night.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/histogram_etaA_night.png
187,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/histogram_residuals.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/histogram_residuals.png
188,raw/EHT2018_metadata_MM/JCMT_2017/JCMT_memo/scuba2.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/JCMT_memo/scuba2.txt
189,raw/EHT2018_metadata_MM/JCMT_2017/aperture_efficiency_test.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/aperture_efficiency_test.png
190,raw/EHT2018_metadata_MM/JCMT_2017/cumulative_stats_night.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/cumulative_stats_night.png
191,raw/EHT2018_metadata_MM/JCMT_2017/cumulative_stats_residuals.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/cumulative_stats_residuals.png
192,raw/EHT2018_metadata_MM/JCMT_2017/etaA_fit_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/etaA_fit_JCMT.png
193,raw/EHT2018_metadata_MM/JCMT_2017/etaA_fits_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/etaA_fits_JCMT.png
194,raw/EHT2018_metadata_MM/JCMT_2017/histogram_etaA_night.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/histogram_etaA_night.png
195,raw/EHT2018_metadata_MM/JCMT_2017/histogram_residuals.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/histogram_residuals.png
196,raw/EHT2018_metadata_MM/JCMT_2017/old/DPFU_fit_JCMT.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/old/DPFU_fit_JCMT.png
197,raw/EHT2018_metadata_MM/JCMT_2017/old/JCMT_DPFU.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MM,JCMT_2017/old/JCMT_DPFU.png